SOURCES = AccountIO.java Account.java TransactionIO.java Transaction.java TransactionProcessor.java
# TESTS = AccountCheckTest.java AccountIOTest.java AccountTest.java AdminCheckTest.java BankTest.java ChangeBalanceTest.java ChangeplanTest.java CreateTest.java DeleteTest.java EnableTest.java MasterAccountTest.java PaybillTest.java ProcLoopTest.java TransactionIOTest.java TransactionTest.java TransferTest.java

all:
	@javac $(SOURCES)

# tests:
# 	@javac $(TESTS)

clean:
	@rm *.class